#!/bin/bash
#curl --dump-header  -v -H "Accept: application/json" -H "Content-Type: application/json" -X POST --data "{\"uid\":12,\"token\":\"asdert\"}" http://localhost:5000/v1/
export http_proxy=''

curl --dump-header  -v -H "Accept: application/json" -H "Content-Type: application/json" -X POST --data "{'cluster':{'name':'test','node-recipes':{\"jobtracker\":1,\"tasktracker\":3},'image-id': 'ubuntu-12.04-amd64.img'}}" http://localhost:5000/v1/

